name: Build and deploy Node.js app to Azure Web App - backendv1

on:
  push:
    branches:
      - finalcld
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-

      - name: npm install, build, and test (Server Only)
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: ./server  # Set the working directory to server

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: server-app
          path: ./server  # Upload the server folder directly

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: server-app
          path: ./server

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6FC5F0C9FEF240BB8F9AE8E4C0587A75 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F8319BA5BEAC4E1198CF9DBA44AD940C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_71D9A362E5C342DCA6E04B32548BCBC4 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'backendv1'
          slot-name: 'Production'
          package: ./server  # Deploy the server directory
