name: Build and deploy Node.js app to Azure Web App - frontendv1

on:
  push:
    branches:
      - nlp
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: npm install and build (Client Only)
        run: |
          npm install --ci
          npm run build --if-present
        working-directory: ./client  # Change to the client folder

      - name: Tar the client build folder for deployment
        run: |
          cd client
          tar -czf ../client.tar.gz -C dist .  # Update to match the correct build folder
        shell: bash

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: client-app
          path: client.tar.gz  # Upload the tar.gz package

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: client-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1B1FA3E1C0BE4B30A25B6E2B9BCF3CF0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D8D3E375A7C34405AAB71299547ACF32 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_23C9575AAC884F9FA2B441F4A4A4504A }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'frontendv1'
          slot-name: 'Production'
          package: client.tar.gz  # Deploy the tar.gz package
