name: Build and deploy Node.js app to Azure Web App - frontendv1

on:
  push:
    branches:
      - nlp
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test (Client Only)
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: ./client  # Change to the client folder
      
      - name: Zip the client folder for deployment (Linux)
        run: |
          zip -r client.zip ./client/*
        shell: bash  # Use bash to run the compression command

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: client-app
          path: client.zip  # Upload the zipped package

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: client-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EE06B25B7FA2432285D9AB5CA74D2F31 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_52503BC1172545D78B216D2870DB5AEA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9C14131A23094A529D407F2007B9C0B1 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'frontendv1'
          slot-name: 'Production'
          package: client.zip  # Deploy the zipped package
